version: "3"

services:
  micronaut-bd:
    container_name: micronault-db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: micronault_db
      POSTGRES_USER: micronault_db
      POSTGRES_DB: micronault_db
    ports:
      - "5432:5432"